---
title: "FBI"

output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(readxl)
library(dplyr)
library(readr)
library(ggplot2)
library(gt)
```

```{r echo = FALSE, include = FALSE}

FBI <- read_csv("FBI Top Ten Most Wanted_Fixed - Sheet1.csv") %>% 
  clean_names() %>% 
  mutate_all(funs(replace_na(., 0))) %>% 
  mutate_if(is.numeric, funs(replace_na(., 0)))

file.copy("FBI Top Ten Most Wanted_Fixed - Sheet1.csv", "final_project")
```

```{r crime_data, echo = FALSE}

crime <- FBI %>% 
  select(-name,
         -placed_on_list,
         - removed_from_list,
         - reason_for_removal,
         - race,
         - gender,
         - nationality,
         - gang_related,
         - police_victim) %>% 
  pivot_longer(everything(),
               names_to = "crime",
               values_to = "count") %>% 
  filter(count == 1) %>% 
  select(crime) %>% 
  count(crime)

crime
```


```{r crime_year, echo = FALSE}
pie_chart <- FBI %>% 
filter(! race == 0) %>% 
       group_by(race) %>% 
       count()  %>% 
       mutate(prop = (n)/(sum(n))) 

pie_chart %>% 
ggplot(aes(x = "", y = n, fill = race))+
       geom_bar(width = 1, stat = "identity") +
       coord_polar("y", start=0) + 
       theme_void() 
```


